// calendar
export const GET_CALENDAR = 'GET_CALENDAR';
export const CALENDAR_SUCCESS = 'CALENDAR_SUCCESS';
export const CALENDAR_ERROR = 'CALENDAR_ERROR';

export const GET_INTERVIEW_LINK = 'GET_INTERVIEW_LINK';
export const INTERVIEW_LINK_SUCCESS = 'INTERVIEW_LINK_SUCCESS';

export const MOVE_NEXT_STEP = 'MOVE_NEXT_STEP';
export const REJECT_CANDIDATE = 'REJECT_CANDIDATE';

// interview
export const GET_FUTURE_INTERVIEW = 'GET_FUTURE_INTERVIEW';
export const FUTURE_INTERVIEW_SUCCESS = 'FUTURE_INTERVIEW_SUCCESS';
export const FUTURE_INTERVIEW_ERROR = 'FUTURE_INTERVIEW_ERROR';
