export const GET_CALENDAR = 'GET_CALENDAR';
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_ERROR = 'GET_CALENDAR_ERROR';
export const GET_INTERVIEW_LINK = 'GET_INTERVIEW_LINK';
